// packages/elu-vue/src/Search.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    placeholder?: string;
    debounceMs?: number;
  }>(),
  { placeholder: 'Search…', debounceMs: 0 },
);
</script>

<template>
  <div data-elu-search>
    <input
      type="search"
      :placeholder="placeholder"
      autocomplete="off"
      autocorrect="off"
      autocapitalize="off"
      spellcheck="false"
      enterkeyhint="search"
      :data-debounce-ms="debounceMs"
    />
  </div>
</template>

// packages/elu-svelte/src/Search.svelte
<script lang="ts">
  export let placeholder: string = 'Search…';
  export let debounceMs: number = 0;
  let className: string = '';
  export { className as class };
</script>

<div data-elu-search class={className}>
  <input
    type="search"
    {placeholder}
    autocomplete="off"
    autocorrect="off"
    autocapitalize="off"
    spellcheck="false"
    enterkeyhint="search"
    data-debounce-ms={debounceMs}
  />
</div>
