// packages/elu-vue/src/Viewport.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{ maxHeight?: string }>();
const style = computed(() => (props.maxHeight ? { maxHeight: props.maxHeight } : undefined));
</script>

<template>
  <div data-elu-viewport :style="style">
    <slot />
  </div>
</template>

// packages/elu-svelte/src/Viewport.svelte
<script lang="ts">
  export let maxHeight: string | number | undefined = undefined;
  let className: string = '';
  export { className as class };
</script>

<div
  data-elu-viewport
  class={className}
  style={maxHeight != null ? `max-height: ${typeof maxHeight === 'number' ? maxHeight + 'px' : maxHeight}` : ''}
>
  <slot />
</div>
