// packages/elu-svelte/src/Content.svelte
<script lang="ts">
  import type { Side, Align } from '@mgasme/elu-core/types';
  export let align: Align = 'start';
  export let side: Side = 'bottom';
  export let sideOffset: number = 4;
  export let collisionPadding: number = 8;
  let className: string = '';
  export { className as class };
</script>

<div
  data-elu-content
  popover="auto"
  class={className}
  data-side={side}
  data-align={align}
  data-side-offset={sideOffset}
  data-collision-padding={collisionPadding}
>
  <slot />
</div>

// packages/elu-react/src/Content.tsx
'use client';

import type { EluContentProps } from '@mgasme/elu-core/types';

type EluContentReactProps = Omit<EluContentProps, 'class'> & {
  className?: string;
  children?: React.ReactNode;
};

export function Content({
  className,
  align = 'start',
  side = 'bottom',
  sideOffset = 4,
  collisionPadding = 8,
  children,
}: EluContentReactProps) {
  return (
    <div
      data-elu-content
      popover="auto"
      className={className}
      data-side={side}
      data-align={align}
      data-side-offset={sideOffset}
      data-collision-padding={collisionPadding}
    >
      {children}
    </div>
  );
}
