// packages/elu-svelte/src/Item.svelte
<script lang="ts">
  export let value: string;
  export let disabled: boolean = false;
  export let textValue: string | undefined = undefined;
  let className: string = '';
  export { className as class };
</script>

<div
  data-elu-item
  data-value={value}
  data-text-value={textValue ?? null}
  data-disabled={disabled ? 'true' : null}
  class={className}
>
  <slot />
</div>

// packages/elu-react/src/Item.tsx
'use client';

import type { EluItemProps } from '@mgasme/elu-core/types';

type EluItemReactProps = Omit<EluItemProps, 'class'> & {
  className?: string;
  children?: React.ReactNode;
};

export function Item({ value, disabled, textValue, className, children }: EluItemReactProps) {
  return (
    <div
      data-elu-item
      data-value={value}
      data-text-value={textValue}
      data-disabled={disabled ? 'true' : undefined}
      className={className}
    >
      {children}
    </div>
  );
}
