// packages/elu-svelte/src/Root.svelte
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte';
  import { EluController } from '@mgasme/elu-core/controller';
  import type { EluChangeDetail, Dir, Size, Theme } from '@mgasme/elu-core/types';

  export let id: string | undefined = undefined;
  export let name: string | undefined = undefined;
  export let defaultValue: string | string[] | undefined = undefined;
  export let value: string | string[] | undefined = undefined;
  export let multiple: boolean = false;
  export let disabled: boolean = false;
  export let required: boolean = false;
  export let dir: Dir = 'ltr';
  export let size: Size | undefined = undefined;
  export let theme: Theme | undefined = undefined;

  let className: string = '';
  export { className as class };

  let rootEl: HTMLDivElement;
  let ctrl: EluController | null = null;

  const dispatch = createEventDispatcher<{ change: EluChangeDetail }>();

  const initialArray: string[] = (() => {
    const src = value ?? defaultValue;
    if (src == null || src === '') return [];
    return Array.isArray(src) ? src.map(String) : [String(src)];
  })();

  function handleChange(e: Event) {
    const detail = (e as CustomEvent<EluChangeDetail>).detail;
    value = detail.value;
    dispatch('change', detail);
  }

  onMount(() => {
    rootEl.dataset.eluBooted = 'true';
    ctrl = new EluController({ root: rootEl });
    rootEl.addEventListener('elu:change', handleChange);
  });

  onDestroy(() => {
    rootEl?.removeEventListener('elu:change', handleChange);
    ctrl?.destroy();
    ctrl = null;
  });

  // Controlled mode: push external value changes into the controller silently.
  $: if (ctrl && value !== undefined) ctrl.setValue(value, { silent: true });
</script>

<div
  bind:this={rootEl}
  data-elu-root
  data-state="closed"
  data-multiple={multiple ? 'true' : null}
  data-disabled={disabled ? 'true' : null}
  data-required={required ? 'true' : null}
  data-size={size ?? null}
  data-theme={theme ?? null}
  data-name={name ?? null}
  data-value-initial={JSON.stringify(initialArray)}
  {dir}
  {id}
  class={className}
>
  <slot />
  <!-- Controller writes hidden form inputs here imperatively. -->
  <span data-elu-form-inputs hidden></span>
</div>

// packages/elu-react/src/Root.tsx
'use client';

import { useLayoutEffect, useRef } from 'react';
import { EluController } from '@mgasme/elu-core/controller';
import type { EluRootProps, EluChangeDetail } from '@mgasme/elu-core/types';

type EluRootReactProps = Omit<EluRootProps, 'class'> & {
  value?: string | string[];
  onValueChange?: (next: string | string[]) => void;
  className?: string;
  children: React.ReactNode;
};

export function Root({
  id,
  name,
  defaultValue,
  value,
  onValueChange,
  multiple,
  disabled,
  required,
  dir = 'ltr',
  size,
  theme,
  className,
  children,
}: EluRootReactProps) {
  const rootRef = useRef<HTMLDivElement>(null);
  const ctrlRef = useRef<EluController | null>(null);
  const onValueChangeRef = useRef(onValueChange);
  onValueChangeRef.current = onValueChange;

  const initialArray: string[] =
    value != null
      ? Array.isArray(value)
        ? value.map(String)
        : value === ''
          ? []
          : [String(value)]
      : Array.isArray(defaultValue)
        ? defaultValue.map(String)
        : defaultValue != null && defaultValue !== ''
          ? [String(defaultValue)]
          : [];

  useLayoutEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    root.dataset.eluBooted = 'true';

    const ctrl = new EluController({ root });
    ctrlRef.current = ctrl;

    const handler = (e: Event) => {
      const detail = (e as CustomEvent<EluChangeDetail>).detail;
      onValueChangeRef.current?.(detail.value);
    };
    root.addEventListener('elu:change', handler);

    return () => {
      root.removeEventListener('elu:change', handler);
      ctrl.destroy();
      ctrlRef.current = null;
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Controlled mode: push external value changes into the controller silently
  useLayoutEffect(() => {
    if (value !== undefined && ctrlRef.current) {
      ctrlRef.current.setValue(value, { silent: true });
    }
  }, [value]);

  return (
    <div
      ref={rootRef}
      data-elu-root
      data-state="closed"
      data-multiple={multiple ? 'true' : undefined}
      data-disabled={disabled ? 'true' : undefined}
      data-required={required ? 'true' : undefined}
      data-size={size}
      data-theme={theme}
      data-name={name}
      data-value-initial={JSON.stringify(initialArray)}
      dir={dir}
      id={id}
      className={className}
    >
      {children}
      {/* Controller writes hidden form inputs here imperatively; React must not reconcile children. */}
      <span data-elu-form-inputs hidden suppressHydrationWarning />
    </div>
  );
}
