// packages/elu-svelte/src/Search.svelte
<script lang="ts">
  export let placeholder: string = 'Search…';
  export let debounceMs: number = 0;
  let className: string = '';
  export { className as class };
</script>

<div data-elu-search class={className}>
  <input
    type="search"
    {placeholder}
    autocomplete="off"
    autocorrect="off"
    autocapitalize="off"
    spellcheck="false"
    enterkeyhint="search"
    data-debounce-ms={debounceMs}
  />
</div>

// packages/elu-react/src/Search.tsx
'use client';

import type { EluSearchProps } from '@mgasme/elu-core/types';

type EluSearchReactProps = Omit<EluSearchProps, 'class'> & {
  className?: string;
};

export function Search({ placeholder = 'Search…', className, debounceMs = 0 }: EluSearchReactProps) {
  return (
    <div data-elu-search className={className}>
      <input
        type="search"
        placeholder={placeholder}
        autoComplete="off"
        autoCorrect="off"
        autoCapitalize="off"
        spellCheck={false}
        enterKeyHint="search"
        data-debounce-ms={debounceMs}
      />
    </div>
  );
}
