// packages/elu-vue/src/Viewport.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{ maxHeight?: string }>();
const style = computed(() => (props.maxHeight ? { maxHeight: props.maxHeight } : undefined));
</script>

<template>
  <div data-elu-viewport :style="style">
    <slot />
  </div>
</template>

// packages/elu-react/src/Viewport.tsx
'use client';

import type { EluViewportProps } from '@mgasme/elu-core/types';

type EluViewportReactProps = Omit<EluViewportProps, 'class'> & {
  className?: string;
  children?: React.ReactNode;
};

export function Viewport({ className, maxHeight, children }: EluViewportReactProps) {
  const style = maxHeight ? { maxHeight } : undefined;
  return (
    <div data-elu-viewport className={className} style={style}>
      {children}
    </div>
  );
}
